# Generated by Django 3.2.6 on 2021-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, default=True, max_length=100, unique=True),
        ),
    ]
