# Generated by Django 3.2.6 on 2021-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20210901_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(db_index=True, default=None, max_length=100),
        ),
    ]
