# Generated by Django 3.2.6 on 2021-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0007_exerciseuse_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseuse',
            name='date_finish',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exerciseuse',
            name='date_start',
            field=models.DateTimeField(auto_created=True, blank=True, default=None, null=True),
        ),
    ]
