# Generated by Django 3.2.6 on 2021-09-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_alter_exerciseuse_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='exercise',
            new_name='exercise_use',
        ),
    ]
