# Generated by Django 3.2.6 on 2021-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_rename_exercise_set_exercise_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100, null=True),
        ),
    ]
