# Generated by Django 3.2.6 on 2021-10-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0011_alter_telegramuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exersice',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
