# Generated by Django 3.2.6 on 2021-10-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0012_exersice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='favorite_exercises',
            field=models.ManyToManyField(related_name='favorited_users', to='webhook.Exersice'),
        ),
    ]
