# Generated by Django 3.2.6 on 2021-10-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0013_telegramuser_favorite_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.exersice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.telegramuser')),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='favorite_exercises',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='favorite_exercises',
            field=models.ManyToManyField(through='webhook.FavoritedExercises', to='webhook.Exersice')
        )
    ]
