# Generated by Django 3.2.6 on 2021-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0015_exersice_details_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseuse',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
