# Generated by Django 3.2.6 on 2021-12-01 17:12

from django.db import migrations

TITLES = ['ноги', 'грудь', 'спина', 'руки', 'плечи']


def combine_categories(apps, schema_editor):
    Category = apps.get_model('webhook', 'Category')
    objects = [Category(title=title) for title in TITLES]
    Category.objects.bulk_create(objects)


def reverse_combine(apps, schema_editor):
    Category = apps.get_model('webhook', 'Category')
    Category.objects.filter(title__in=TITLES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('webhook', '0017_alter_exersice_description'),
    ]

    operations = [
        migrations.RunPython(combine_categories, reverse_combine)
    ]
