# Generated by Django 3.2.6 on 2021-12-01 18:30

from django.db import migrations

EXERCISES = {
    'ноги': ['Приседания со штангой на спине',
             'Приседания со штангой на груди',
             'Выпады',
             'Жим ногами в тренажёре',
             'Сведения на тренажёре',
             'Подъёмы на носки стоя'],
    'грудь': ['Жим штанги лёжа',
              'Жим гантелей лёжа',
              'Сведение рук на тренажёре-бабочке',
              'Сведение рук накрест в кроссовере',
              'Разведение гантелей на скамье',
              'Отжимание на брусьях',
              'Отжимание на петлях'],
    'спина': ['Тяга верхнего блока к груди',
              'Тяга нижнего блока к животу',
              'Подтягивания прямым хватом',
              'Тяга штанги в наклоне',
              'Тяга штанги к подбородку',
              'Становая тяга'],
    'руки': ['Концентрированные подъёмы на бицепс',
             'Подъём штанги или гантелей на бицепс',
             'Отжимания на брусьях',
             'Разгибание на трицепс с гантелью',
             'Алмазные отжимания'],
    'плечи': ['Жим штанги или гантелей стоя',
              'Разводка гантелей в стороны',
              'Разводка в наклоне']
}


def combine_exercises(apps, schema_editor):
    Category = apps.get_model('webhook', 'Category')
    Exersice = apps.get_model('webhook', 'Exersice')
    objects = []
    for category_name in EXERCISES:
        category_list = Category.objects.filter(title=category_name)
        if category_list:
            category = category_list.first()
            objects.extend(
                [Exersice(title=exercise_name, category_id=category.id) for exercise_name in EXERCISES[category_name]]
            )
    Exersice.objects.bulk_create(objects)


def reverse_combine(apps, schema_editor):
    Exersice = apps.get_model('webhook', 'Exersice')
    titles = [exercise for category, exercises in EXERCISES.items() for exercise in exercises]
    Exersice.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('webhook', '0018_auto_20211201_2012'),
    ]

    operations = [
        migrations.RunPython(combine_exercises, reverse_combine)
    ]
