# Generated by Django 3.2.6 on 2022-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0022_alter_telegramuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='function',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
