# Generated by Django 3.2.6 on 2022-02-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0023_view_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='new_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='webhook.state'),
        ),
    ]
