# Generated by Django 3.2.6 on 2022-02-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0026_view_keyboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replybutton',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='webhook.keyboard'),
        ),
    ]
