# Generated by Django 3.2.6 on 2022-02-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0027_alter_replybutton_keyboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhook.replybutton'),
        ),
    ]
