# Generated by Django 3.2.6 on 2022-02-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0028_state_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name_parameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.telegramuser')),
            ],
            options={
                'unique_together': {('state', 'user')},
            },
        ),
    ]
