# Generated by Django 3.2.6 on 2022-02-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0029_auto_20220207_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exersice',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='exersice',
            name='image',
        ),
    ]
