# Generated by Django 3.2.6 on 2022-02-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0030_auto_20220207_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='translate_state_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views_traslated', to='webhook.state'),
        ),
        migrations.AlterField(
            model_name='view',
            name='new_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views_new', to='webhook.state'),
        ),
    ]
