name: Django CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Start containers
      run: docker run -d --name db --env-file "keys.txt" -p 5432:5432 -v "/media":"/media" postgres 
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: migrate
      run: |
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
